disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - trailing_whitespace
  - opening_brace
  - function_parameter_count
  - nesting
opt_in_rules: # some rules are only opt-in
  - empty_count
  - implicit_return
  - toggle_bool
  - contains_over_filter_is_empty
  - contains_over_filter_count
  - collection_alignment
  - contains_over_first_not_nil
  - force_unwrapping
  - unused_import
  - empty_string
  - fatal_error_message
  - closure_spacing
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - UDFReduxApp
  - SideEffects
  - Foundation
  - Flows
  - Core
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Resources
        
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 160
# they can set both implicitly with an array

type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 600
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded:
    - iPhone # excluded via string
    - API
    - Key
    - C
    - ID
    - R
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
    - Self
    - x
    - y
    - z
    - _self
    - vc
    - vm
    - am
    - pm
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
